-- Drop existing tables if they exist
DROP TABLE IF EXISTS audit_log CASCADE;
DROP TABLE IF EXISTS category_ticket CASCADE;
DROP TABLE IF EXISTS comment_ticket CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS ticket CASCADE;

-- Create audit_log table
CREATE TABLE audit_log (
    employee_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ticket_id BIGINT,
    timestamp TIMESTAMP(6),
    details VARCHAR(255),
    action ENUM('ADD_COMMENT', 'CHANGE_STATUSES'),
    PRIMARY KEY (id)
);

-- Create category_ticket table
CREATE TABLE category_ticket (
    categoryid BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ticket_id BIGINT,
    category_name VARCHAR(255),
    PRIMARY KEY (categoryid)
);

-- Create comment_ticket table
CREATE TABLE comment_ticket (
    date_created TIMESTAMP(6),
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ticket_id BIGINT,
    content VARCHAR(255),
    PRIMARY KEY (id)
);

-- Create employee table
CREATE TABLE employee (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR(255),
    password VARCHAR(255),
    username VARCHAR(255),
    role ENUM('ItSupport', 'employee'),
    PRIMARY KEY (id)
);


-- Create ticket table
CREATE TABLE ticket (
    category_categoryid BIGINT,
    created_at TIMESTAMP(6),
    employee_id BIGINT,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    updated_at TIMESTAMP(6),
    description VARCHAR(255),
    title VARCHAR(255),
    priority_level ENUM('HIGH', 'LOW', 'MEDIUM'),
    status_tracking ENUM('In_Progress', 'New', 'Resolved'),
    PRIMARY KEY (id)
);

-- Add foreign key constraints
ALTER TABLE IF EXISTS audit_log
    ADD CONSTRAINT FK_iamw6l6afghnuqa7xtpdolkk0
    FOREIGN KEY (employee_id) REFERENCES employee;

ALTER TABLE IF EXISTS audit_log
    ADD CONSTRAINT FK_q29csl9wg9y418qj28vmddnuo
    FOREIGN KEY (ticket_id) REFERENCES ticket;

ALTER TABLE IF EXISTS category_ticket
    ADD CONSTRAINT FK_8pygcc82km01pca64xxmaw5gt
    FOREIGN KEY (ticket_id) REFERENCES ticket;

ALTER TABLE IF EXISTS comment_ticket
    ADD CONSTRAINT FK_bd4x9v7k78i36d37qdhyn6owa
    FOREIGN KEY (employee_id) REFERENCES employee;

ALTER TABLE IF EXISTS comment_ticket
    ADD CONSTRAINT FK_ncqvde1tk9vblma6nhq5x75bb
    FOREIGN KEY (ticket_id) REFERENCES ticket;

ALTER TABLE IF EXISTS ticket
    ADD CONSTRAINT FK_jmyy3uuro6my3ufkstngo30hw
    FOREIGN KEY (category_categoryid) REFERENCES category_ticket;

ALTER TABLE IF EXISTS ticket
    ADD CONSTRAINT FK_a78dsu86la2dni050sh6gap19
    FOREIGN KEY (employee_id) REFERENCES employee;
